server:
  port: 80
logging: 
  level:
    suntion: debug
spring: 
  datasource: 
    data-url: suntion.cc:3306/auth-dev
    username: root
    password: rootabc,123
  redis:
    database: 0
    host: suntion.cc
    password: rootabc,123
    port: 6379
  thymeleaf:
    cache: false